# Generated by Django 6.0.4 on 2026-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Admin Settings',
            },
        ),
    ]
