# Generated by Django 6.0.4 on 2026-05-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_beds', models.IntegerField()),
                ('respite_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShelterInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('shelter', models.CharField(max_length=100)),
                ('regular', models.IntegerField()),
                ('respite', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('jail', models.IntegerField()),
                ('no_show', models.IntegerField()),
                ('barred', models.IntegerField()),
                ('hold', models.IntegerField()),
            ],
        ),
    ]
