# Generated by Django 6.0.4 on 2026-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterInputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter', models.CharField(max_length=100)),
                ('regular_occupied', models.IntegerField()),
                ('regular_open', models.IntegerField()),
                ('guests_on_pass', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('jail', models.IntegerField()),
                ('nc_ns', models.IntegerField()),
                ('barred', models.IntegerField()),
                ('hold', models.IntegerField()),
                ('respite_occupied', models.IntegerField()),
                ('respite_open', models.IntegerField()),
            ],
        ),
    ]
