# Generated by Django 6.0.3 on 2026-03-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=50)),
                ('beds_used', models.IntegerField()),
                ('beds_available', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
            ],
        ),
    ]
